services:
  localstack:
    image: localstack/localstack
    environment:
      AWS_ACCESS_KEY_ID: testKey
      AWS_SECRET_ACCESS_KEY: testSecret
      AWS_DEFAULT_REGION: eu-central-1
      SERVICES: dynamodb
    ports:
      - "4566:4566"